import {PDFDocument} from "pdf-lib";import {COMMERCIAL_2350} from "./hangul";import {cellParts,LAYOUT} from "./layout";
const MM_W=210,MM_H=297,SCALE=5.9;
function blobBytes(canvas:HTMLCanvasElement){return new Promise<Uint8Array>((resolve,reject)=>canvas.toBlob(async b=>b?resolve(new Uint8Array(await b.arrayBuffer())):reject(new Error("가이드 이미지를 만들지 못했습니다.")),"image/jpeg",.92))}
export async function makeGuide(onProgress?:(n:number)=>void){const doc=await PDFDocument.create(),chars=COMMERCIAL_2350,l=LAYOUT,pages=Math.ceil(chars.length/l.perPage),canvas=document.createElement("canvas");canvas.width=Math.round(MM_W*SCALE);canvas.height=Math.round(MM_H*SCALE);const ctx=canvas.getContext("2d")!,x=(mm:number)=>mm*SCALE,y=(mm:number)=>mm*SCALE;
 doc.setTitle(`글씨담 2,350자 손글씨 가이드`);doc.setSubject(`GEULSSIDAM:2350:${chars.length}:v2-initial-guide`);doc.setCreator("글씨담");
 for(let p=0;p<pages;p++){ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.textBaseline="middle";ctx.textAlign="left";ctx.fillStyle="#182019";ctx.font=`700 ${y(4.5)}px "Malgun Gothic",sans-serif`;const label="한글 2,350자";ctx.fillText(`글씨담 · ${label} 손글씨 가이드`,x(12),y(9.5));ctx.textAlign="right";ctx.fillStyle="#526056";ctx.font=`500 ${y(2.8)}px "Malgun Gothic",sans-serif`;ctx.fillText(`${p+1} / ${pages}`,x(198),y(9.5));ctx.textAlign="left";ctx.font=`400 ${y(2.5)}px "Malgun Gothic",sans-serif`;ctx.fillText("상단 보기 글자를 확인하고, 안쪽 글자 영역의 70-85%를 채워 자연스럽게 써주세요.",x(12),y(16));ctx.textAlign="right";ctx.fillStyle="#768078";ctx.fillText("페이지 순서를 유지해 주세요",x(198),y(16));
  ctx.fillStyle="#111";for(const [mx,my] of [[8,22],[199,22],[8,284],[199,284]])ctx.fillRect(x(mx),y(my),x(3),y(3));
  for(let k=0;k<l.perPage;k++){const idx=p*l.perPage+k,{cell:b,dividerY,writing}=cellParts(k);ctx.strokeStyle="#cbd0ca";ctx.lineWidth=Math.max(1,x(.12));ctx.strokeRect(x(b.x),y(b.y),x(b.w),y(b.h));ctx.strokeStyle="#d6dad5";ctx.beginPath();ctx.moveTo(x(b.x+1),y(dividerY));ctx.lineTo(x(b.x+b.w-1),y(dividerY));ctx.stroke();ctx.strokeStyle="#dfe3de";ctx.lineWidth=Math.max(1,x(.10));ctx.strokeRect(x(writing.x),y(writing.y),x(writing.w),y(writing.h));if(idx>=chars.length)continue;ctx.fillStyle="#899089";ctx.textAlign="left";ctx.font=`600 ${y(2.35)}px "Malgun Gothic",sans-serif`;ctx.fillText(String(idx+1),x(b.x+1.2),y(b.y+b.h*.125));ctx.textAlign="right";ctx.fillStyle="#596159";ctx.font=`600 ${y(3.2)}px "Malgun Gothic",sans-serif`;ctx.fillText(chars[idx],x(b.x+b.w-1.4),y(b.y+b.h*.125))}
  const jpg=await doc.embedJpg(await blobBytes(canvas)),page=doc.addPage([595.28,841.89]);page.drawImage(jpg,{x:0,y:0,width:595.28,height:841.89});onProgress?.(Math.round((p+1)/pages*100));await new Promise(requestAnimationFrame);
 }return doc.save()}
export function saveBytes(bytes:Uint8Array,name:string,type="application/pdf"){const blob=new Blob([bytes as BlobPart],{type}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
