import opentype from "opentype.js";import type {GlyphRaster} from "./extract";import {writeTTF} from "./ttf";
export type Region={x0:number;y0:number;x1:number;y1:number};export type Pt=[number,number];export type Prepared={points:Pt[];corners:boolean[]};
/** 윤곽 점(약 1px 간격)을 윤곽을 따라 가우시안으로 평활화해 계단 모양을 없앱니다. 작은 윤곽은 모양이 무너지지 않게 약하게 적용합니다. */
function gaussSmooth(points:Pt[],sigma:number):Pt[]{const n=points.length,s=Math.min(sigma,n/10);if(s<.5)return points;const R=Math.ceil(s*2.5),w:number[]=[];let total=0;for(let k=-R;k<=R;k++){const v=Math.exp(-k*k/(2*s*s));w.push(v);total+=v}return points.map((_,i):Pt=>{let x=0,y=0;for(let k=-R;k<=R;k++){const p=points[((i+k)%n+n)%n],v=w[k+R];x+=p[0]*v;y+=p[1]*v}return [x/total,y/total]})}
function simplify(points:Pt[],epsilon:number){if(points.length<5)return points;const lineDistance=(p:Pt,a:Pt,b:Pt)=>{const dx=b[0]-a[0],dy=b[1]-a[1];if(!dx&&!dy)return Math.hypot(p[0]-a[0],p[1]-a[1]);const t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(dx*dx+dy*dy)));return Math.hypot(p[0]-(a[0]+t*dx),p[1]-(a[1]+t*dy))};const run=(arr:Pt[]):Pt[]=>{let max=0,index=0;for(let i=1;i<arr.length-1;i++){const d=lineDistance(arr[i],arr[0],arr[arr.length-1]);if(d>max){max=d;index=i}}if(max>epsilon){const left=run(arr.slice(0,index+1)),right=run(arr.slice(index));return left.slice(0,-1).concat(right)}return [arr[0],arr[arr.length-1]]};const closed=[...points,points[0]],result=run(closed);result.pop();return result.length>=3?result:points}
/** raw: 약 1px 간격으로 늘어선 닫힌 윤곽. 평활화 → 단순화 후, 급하게 꺾이는 점(90° 넘게)만 모서리로 남기고 나머지는 곡선으로 잇습니다. */
export function prepContour(raw:Pt[],epsilon:number,sigma=1.8):Prepared|null{if(raw.length<4)return null;const points=simplify(gaussSmooth(raw,sigma),epsilon);if(points.length<3)return null;const corner=(i:number)=>{const prev=points[(i-1+points.length)%points.length],p=points[i],next=points[(i+1)%points.length],ax=p[0]-prev[0],ay=p[1]-prev[1],bx=next[0]-p[0],by=next[1]-p[1],length=Math.hypot(ax,ay)*Math.hypot(bx,by);return length>0&&(ax*bx+ay*by)/length<0};return {points,corners:points.map((_,i)=>corner(i))}}
export function emitContour(path:opentype.Path,pc:Prepared,map:(point:Pt)=>Pt){const {points,corners}=pc,mapped=points.map(map),first=mapped[0];path.moveTo(first[0],first[1]);for(let i=0;i<mapped.length;i++){const p=mapped[i],q=mapped[(i+1)%mapped.length],prev=mapped[(i-1+mapped.length)%mapped.length],after=mapped[(i+2)%mapped.length],c1:Pt=corners[i]?p:[p[0]+(q[0]-prev[0])*.16,p[1]+(q[1]-prev[1])*.16],c2:Pt=corners[(i+1)%mapped.length]?q:[q[0]-(after[0]-p[0])*.16,q[1]-(after[1]-p[1])*.16];if(corners[i]&&corners[(i+1)%mapped.length])path.lineTo(q[0],q[1]);else path.curveTo(c1[0],c1[1],c2[0],c2[1],q[0],q[1])}path.close()}
export function inkRegion(r:GlyphRaster,padding=2):Region{let minX=r.width,minY=r.height,maxX=-1,maxY=-1;for(let y=0;y<r.height;y++)for(let x=0;x<r.width;x++)if(r.data[y*r.width+x]){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y)}if(maxX<0)return {x0:0,y0:0,x1:1,y1:1};return {x0:Math.max(0,minX-padding)/r.width,y0:Math.max(0,minY-padding)/r.height,x1:Math.min(r.width,maxX+1+padding)/r.width,y1:Math.min(r.height,maxY+1+padding)/r.height}}
export function normalizedTarget(region:Region,r:GlyphRaster):Region{const aspect=((region.x1-region.x0)*r.width)/((region.y1-region.y0)*r.height),max=.88;let w=max,h=max;if(aspect>1)h=max/aspect;else w=max*aspect;return {x0:(1-w)/2,y0:(1-h)/2,x1:(1+w)/2,y1:(1+h)/2}}
export function glyph(c:string,path:opentype.Path){let minX=Infinity,maxX=-Infinity;for(const command of path.commands){const q=command as typeof command&{x?:number;x1?:number;x2?:number};for(const k of ["x","x1","x2"] as const){const v=q[k];if(v!==undefined){q[k]=v*.92;minX=Math.min(minX,q[k]!);maxX=Math.max(maxX,q[k]!)}}}if(!Number.isFinite(minX)){minX=0;maxX=630}const margin=45,shift=margin-minX;for(const command of path.commands){const q=command as typeof command&{x?:number;x1?:number;x2?:number};if(q.x!==undefined)q.x+=shift;if(q.x1!==undefined)q.x1+=shift;if(q.x2!==undefined)q.x2+=shift}const advanceWidth=Math.max(720,Math.min(920,Math.ceil(maxX-minX+margin*2)));return new opentype.Glyph({name:`uni${c.charCodeAt(0).toString(16).toUpperCase()}`,unicode:c.charCodeAt(0),advanceWidth,path})}
/** TTF를 만들어 내려받습니다. opentype.js의 toArrayBuffer()는 11,172자에서 1분 넘게 멈추므로 직접 쓴 writeTTF를 씁니다. */
export function downloadFont(font:opentype.Font,name:string){const glyphs=Array.from({length:font.glyphs.length},(_,i)=>font.glyphs.get(i)),arrayBuffer=writeTTF(glyphs,name.trim()||"MyHandwriting"),parsed=opentype.parse(arrayBuffer);if(parsed.glyphs.length!==glyphs.length)throw new Error("생성된 TTF의 글리프 수가 올바르지 않습니다.");const blob=new Blob([arrayBuffer],{type:"font/ttf"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${name.replace(/[\\/:*?"<>|]/g,"-")||"geulssidam"}.ttf`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
